### ISSUE TITLE
[Feature] - Document advantages of hexagonal architectures

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/miranum-docs#39]
- [x] Description created
- [x] Reviewed by peer: @rami-nk 
- [x] Prioritised

# Description
We want to create a best-practice in our documentation highlighting the advantages of a hexagonal architecture compared to a layered approach. This can act as a foundation for the further miranum-connect docu pages which build upon these architectural foundations 

## Sub-Tasks
```[tasklist]
### Tasks
- [ ] Write a chapter about the hexagonal architecture 
- [ ] Compare it to the layered architecture 
- [ ] Get a writing review
```
```[tasklist]
### Optional 
- [ ] Publish findings in a blogposts as well
```

**Comment by rami-nk** [comment]
We should also add a reference to it in the existing chapters where the knowledge is a prerequisite. And maybe the package structure of the hexagonal architecture can be a subsection and we can refer to it when every needed.
